name: Publish Docker image

env:
  IMAGE_NAME: seal-python
on:
  push:    # Publish `master` as Docker `latest` image.
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [published]
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          dockerfile: docker/Dockerfile
          repository: ${{ github.repository }}/$IMAGE_NAME
          tag_with_ref: true
